version: '3.7'

services:
  django:
    build: .
    ports:
      - "8000:8000"
    command: ["sh", "-c", "python3 manage.py migrate && python3 manage.py index_files && python manage.py runserver 0.0.0.0:8000"]
    volumes:
      - .:/project
